### ISSUE TITLE
Could not exit apartment once after drinking undead potion

### ISSUE THREAD

**Issue by dddanger** [scrudgey/yogurt#104]
Weird corner case bug. I was blending and mixing potions, drank the undead potion. I was unable to exit the apartment after doing this. The teleport command initiated the location selection menu and animation, but didn't end up teleporting. Sleep also didn't work. The head expode button did work and I was able to get past the bug.

**Comment by scrudgey** [comment]
sounds related to a similar liquid liquid serialization issue

**Comment by scrudgey** [comment]
related to #100 , closing for now
