### ISSUE TITLE
Falling into death cave 2 and landing on the moon sometimes loses held items

### ISSUE THREAD

**Issue by dddanger** [scrudgey/yogurt#105]
The animations for falling into death cave 2 and landing on the moon sometimes fling the currently held item off screen. It seems like a random pain in the ass to lose the item sometimes. It would be better to store the held item in inventory before the animation???

**Comment by duckmammal** [comment]
this also happened to me when i fell into the tomb of the king that had ichor in it

**Comment by scrudgey** [comment]
fixed
