### ISSUE TITLE
Character resolution is really low??

### ISSUE THREAD

**Issue by dddanger** [scrudgey/yogurt#113]
The characters are only ~4-5 pixels wide and seem like they're being undersampled or something... Is there a way to change the game resolution that I'm not seeing?

**Comment by scrudgey** [comment]
does it look like bill's problem? https://github.com/scrudgey/yogurt/issues/83

 are you on windows?

**Comment by dddanger** [comment]
Yes windows 10. This is this same issue as #83

**Comment by scrudgey** [comment]
there are two new builds in the google drive directory labeled "bill_hotfix_1" and "bill_hotfix_2", can you tell me if either fixes the problem?

**Comment by dddanger** [comment]
Fixed with "bill_hotfix_1"

**Comment by scrudgey** [comment]
fixed
