### ISSUE TITLE
Can get anti-mayor outfit after nullifying anti-mayor

### ISSUE THREAD

**Issue by dddanger** [scrudgey/yogurt#114]
Can get the anti-mayor outfit after nullifying the anti-mayor and re-entering the anti-mayor screen.

**Comment by scrudgey** [comment]
how does this work? i don't fully understand

**Comment by dddanger** [comment]
I nullified the anti-mayor. He disappeared. I then went up the ladder to the roof scene then went back into the mayor's scene. The anti-mayor outfit was sitting in the middle of the floor.

**Comment by scrudgey** [comment]
that's crazy and definitely not expected behavior

**Comment by scrudgey** [comment]
fixed
