### ISSUE TITLE
you might have enough oxygen to do everyhing on the moon w/o undead or potions

### ISSUE THREAD

**Issue by tim-win** [scrudgey/yogurt#116]
This is up to you, but after doing the gravy commercial without any of the prereq stuff it seems like it mixed up some of the game ordering (also it made missing the silver sword easy because youre in such a rush)

**Comment by scrudgey** [comment]
yes, ive been thinking about this for almost a year. it's possible that some of the other gravy commercials will take longer, you might need to bring the mayor to the moon for an extended sequence, or maybe i just keep things as is and say that teleport scumming is an equally valid solution to this part of the puzzle
