### ISSUE TITLE
the crafting system is really difficult to use

### ISSUE THREAD

**Issue by tim-win** [scrudgey/yogurt#120]
it's a lot of clicks on floating, non-deterministic menus to get anything done here

**Comment by billfreeman44** [comment]
Maybe allow two (or more?) ingredients in the blender at once before blending.

**Comment by billfreeman44** [comment]
oh. @tim-win and @scrudgey what would you think about two potential perks:

- stomach blender: just eat two ingredients and then your stomach blends them together.  Could even be a sidegrade and hurt the user for using the ability
- window to the stomach: see stomach contents

**Comment by scrudgey** [comment]
Hopefully this is all a little easier now. Right click does some quick actions. Blender can contain two items. 

re: bill, now when you have both eating and vomiting perk, UI displays what is in your stomach.

I'm toying with the idea of having first-letter-key hotkeys for action buttons, but that's gonna be kinda difficult to implement. Open to suggestions here.
