### ISSUE TITLE
Possible to interact with objects that are behind impenetrable walls

### ISSUE THREAD

**Issue by duckmammal** [scrudgey/yogurt#121]
I feel like i shouldn't be able to eat this bit of potion that was left behind, because it's underneath the bridge.
![image](https://user-images.githubusercontent.com/4755233/78507433-caa46e80-7734-11ea-87f4-8aa0fe66d544.png)
Maybe it's just a hard to remove artifact of the 2.5 D gaming engine

**Comment by scrudgey** [comment]
It would be possible to do ray-tracing between your character and the object to determine if it's behind a wall, but I feel like that will introduce an insane amount of edge cases and that the system works well enough for the most part as is
