### ISSUE TITLE
Scorpion gang lives at my place now

### ISSUE THREAD

**Issue by duckmammal** [scrudgey/yogurt#123]
Dunno if this is a bug or a humble brag
![image](https://user-images.githubusercontent.com/4755233/78508015-9468ee00-7738-11ea-97bb-cbd0bd4b33e1.png)
I started the Scorpion Gang commercial in my house (with the closet camera) then teleported away, and exploded my head. the next day, the scorpion gang were all just hanging out while peter picklebottom was cleaning up my discarded PJs.

I took out another camera and started another scorpion gang commercial in my house and even more members joined in
![image](https://user-images.githubusercontent.com/4755233/78508068-fcb7cf80-7738-11ea-84be-34e8f4b6078e.png)

I exploded head in my house (without teleporting away) and the new members of the scorpion gang did not stay.

Exploded my head and started the scorpion gang commercial, and then stopped it 3 times in a row.
This caused there to be a huge number of gang members in my house, and also an amazing amount of lag.
![image](https://user-images.githubusercontent.com/4755233/78508326-de52d380-773a-11ea-87a1-ceda89fa9f13.png)

**Comment by scrudgey** [comment]
lmao

**Comment by dddanger** [comment]
Related: dead bodies don't clear each day.

![image](https://user-images.githubusercontent.com/8406272/78511701-c0459d00-7753-11ea-9c6e-f4bc58216a86.png)

**Comment by scrudgey** [comment]
fixed. nobody will be in your apartment when you awake. if you had houseguests, presumably they left after you went to sleep.
