### ISSUE TITLE
Peter Picklebottom won't leave

### ISSUE THREAD

**Issue by duckmammal** [scrudgey/yogurt#124]
After inviting the scorpion gang to my house i basically couldn't do anything there anymore because the lag was so staggering.

The first day he came and took my PJs and the camera away.
The second day he could only take my PJs because there was nothing else for him to take, so now I think he's walking to each member of the scorpion gang and trying to pick them up
![image](https://user-images.githubusercontent.com/4755233/78508551-7d2bff80-773c-11ea-9272-91fde76ab30c.png)

![image](https://user-images.githubusercontent.com/4755233/78508555-81f0b380-773c-11ea-9708-acab54ee6e8a.png)
![image](https://user-images.githubusercontent.com/4755233/78508558-87e69480-773c-11ea-8a27-51a4dfc9edbd.png)

![image](https://user-images.githubusercontent.com/4755233/78508559-8d43df00-773c-11ea-856b-921de358ae29.png)

![image](https://user-images.githubusercontent.com/4755233/78508561-93d25680-773c-11ea-997f-1ee21a48e5fe.png)

**Comment by duckmammal** [comment]
Update, he randomly disappeared from the screen after a few minutes of walking about and picking up nothing.

**Comment by scrudgey** [comment]
he might be taking their switchblades but this is weird

**Comment by scrudgey** [comment]
oh would you look at that

<img width="714" alt="Screen Shot 2020-04-16 at 20 47 01" src="https://user-images.githubusercontent.com/11416012/79530245-a6456d80-8023-11ea-90a7-deb7b01e2e77.png">

**Comment by scrudgey** [comment]
PPB is faster, he will collect between 5 and 10 items max, he speeds up with each item he collects.
