### ISSUE TITLE
atticExit name is incongruent with other names

### ISSUE THREAD

**Issue by duckmammal** [scrudgey/yogurt#125]
Seems like there should be better capitalization or whatnot
![image](https://user-images.githubusercontent.com/4755233/78509104-7c956800-7740-11ea-8f9a-9453bea2e3d6.png)

**Comment by duckmammal** [comment]
It's expecially weird because you don't need to click the exit to use it. You can just keep walking up the stairs.

**Comment by scrudgey** [comment]
fixed
