### ISSUE TITLE
Eggplant commercial not satisfied by blending ingredients together

### ISSUE THREAD

**Issue by duckmammal** [scrudgey/yogurt#127]
Blending eggplant and yogurt on camera together makes a strength potion, which doesn't satisfy the conditions for making a healthy eggplant commercial.

I guess this makes sense at some level, because drinking a strength potion shouldn't satisfy eggplant commercial, but i was bummed when i couldn't get it to work how i wanted.

**Comment by scrudgey** [comment]
marked bug, drinking eggplant juice should still count

**Comment by scrudgey** [comment]
fixed
