### ISSUE TITLE
Hypnotizing moon-person results in oxygen-dependency

### ISSUE THREAD

**Issue by dddanger** [scrudgey/yogurt#132]
When I hypnotize a moon person they suddenly require oxygen. I enter the gravy commercial studio with them and the oxygen meter goes away, does not decrease anymore. The oxygen meter does not decrease upon leaving the gravy commercial studio.

**Comment by dddanger** [comment]
I'm assuming the oxygen dependency isn't intended because they are technically already living on the moon...

**Comment by scrudgey** [comment]
fixed
