### ISSUE TITLE
Feature request: multiple-selection closet inventory

### ISSUE THREAD

**Issue by dddanger** [scrudgey/yogurt#134]
Use a multi-select and drag system to drag items from the apartment closet to your inventory (both shown as side-by-side lists). Either that or checkbox + transfer left/right button. A checkbox in the closet/inventory dialogue to select clothing or hats to immediately wear would be nice too.

**Comment by billfreeman44** [comment]
Maybe right click -> add to inventory

**Comment by scrudgey** [comment]
gonna put this under #91 and solve multiple things in one go
