### ISSUE TITLE
Computer chair seems to get transported to odd locations within my house

### ISSUE THREAD

**Issue by billfreeman44** [scrudgey/yogurt#136]
![Untitled](https://user-images.githubusercontent.com/7268131/78519297-f7866f00-7790-11ea-91fc-45a359fd4806.png)

**Comment by billfreeman44** [comment]
PS, that dead body of myself has been there for like 30 days lol

**Comment by billfreeman44** [comment]
IT KEEPS GOING UP 

![Untitled](https://user-images.githubusercontent.com/7268131/78521606-661afb00-7798-11ea-81be-17b8fc18773d.png)

**Comment by dddanger** [comment]
Same thing with the bodies, chairs... really any object that PPB can't steal.

**Comment by scrudgey** [comment]
fixed. bodies disappear, chair resets.
