### ISSUE TITLE
Clothes/robes ended up in strange location

### ISSUE THREAD

**Issue by billfreeman44** [scrudgey/yogurt#140]
It seemed to happen after I killed the towns people, went into anti-mayor house, went to roof, stabbed the wall (which destroyed it), then went back outside.

![odd_clothing_position](https://user-images.githubusercontent.com/7268131/78520692-71205c00-7795-11ea-9cbe-6a43f80e25be.png)

**Comment by scrudgey** [comment]
i know what this is, it's related to #114
