### ISSUE TITLE
I can make the IMP read the book or spray him with fire extinguisher

### ISSUE THREAD

**Issue by billfreeman44** [scrudgey/yogurt#144]
![imp1](https://user-images.githubusercontent.com/7268131/78582467-4b31a080-7803-11ea-9e04-c574be5863ee.png)

![imp2](https://user-images.githubusercontent.com/7268131/78582473-4cfb6400-7803-11ea-82d0-5442b239339b.png)

**Comment by scrudgey** [comment]
fixed
