### ISSUE TITLE
scrolling in the closet (and other?) menus is very slow

### ISSUE THREAD

**Issue by billfreeman44** [scrudgey/yogurt#145]
![scrolling](https://user-images.githubusercontent.com/7268131/78627590-de98bf00-785f-11ea-87f9-0f835eaf5cd5.gif)

**Comment by scrudgey** [comment]
i cranked up the scroll sensitivity, this will need to be tested later. should also bump the other scroll views in the game too.

**Comment by scrudgey** [comment]
duplicate of #70
