### ISSUE TITLE
clothes don't stay on

### ISSUE THREAD

**Issue by cccCody** [scrudgey/yogurt#146]
i went to the dresser first thing, to try to get dressed for the day. when i "wear" the shirt or pajamas, they get centered over my body, but when i move away, they don't stay on me. they're just left in place where i put them on

**Comment by scrudgey** [comment]
when you click on clothes in the dresser menu, your character will put on those clothes and the clothes they are currently wearing will be removed and put on the floor (currently). if you are wearing pajamas and click on the pajamas from the dresser, you will put on the new pajamas and your old pajamas will end up on the floor, creating the appearance of hte above bug, possibly. please confirm if this makes sense or if you're really seeing a bug (probably gonna change the dresser interaction after some feedback)

**Comment by cccCody** [comment]
ohhhhh i was confused by the old clothes coming off and staying there
