### ISSUE TITLE
Can't seem to self immolate, die in combat, or die by misadventure.

### ISSUE THREAD

**Issue by billfreeman44** [scrudgey/yogurt#152]
lighting self on fire by picking up log in mayors house, walking into volcano, all standing on the lighter, all don't seem to work.

For combat, Scorpion gang can't actually kill me, vampyr can't kill me, knight death doesn't count, and I can't seem to find any other combat stuff to kill me.

I've died almost every way due to whatever traps, but misadventure count is at 0

**Comment by ryan-foltz-exa** [comment]
yep there are some known issues with the achievement tracking, I thought I caught them all but I guess not. it may be random things that trigger these achievements, or nothing at all. e.g. sassing the mayor used to give you the auto-nullification achievement.

**Comment by scrudgey** [comment]
fixed, and rebalanced combat / damage, fixed some damage bugs too. crazy shit
