### ISSUE TITLE
I really want to throw stuff off the cliff but its blocked by an invisible wall 

### ISSUE THREAD

**Issue by billfreeman44** [scrudgey/yogurt#155]
![CLIFFTHROW](https://user-images.githubusercontent.com/7268131/78825120-69d39b00-79ad-11ea-8d8f-f5f8c52bfddb.png)

**Comment by scrudgey** [comment]
this is a big open known issue, but i'll get around to resolving it soon

**Comment by scrudgey** [comment]
finally got around to resolving this issue.
