### ISSUE TITLE
Hold fridge while exiting house doesn't work as intended

### ISSUE THREAD

**Issue by duckmammal** [scrudgey/yogurt#156]
The clicking the door to leave the house has both exit and open, while holding the fridge

![image](https://user-images.githubusercontent.com/4755233/78863633-f05c9c80-79ee-11ea-8fc8-64ee07701ef9.png)

Clicking "open" causes you to open the fridge, which is weird.

Clicking "exit" causes you to exit the house... without the fridge, which is weird.

![image](https://user-images.githubusercontent.com/4755233/78863704-17b36980-79ef-11ea-92a9-8b7c68aa4ac3.png)

**Comment by duckmammal** [comment]
Apparently this may be true for other exiting the house while holding useable items.

![image](https://user-images.githubusercontent.com/4755233/78868939-9bbe1f00-79f8-11ea-913f-f0b86f78f1af.png)

Here Bengis is holding a lighter, and I'm given the option of Exit or Fire.

I tried for a few other items (potion, duplicator) but didn't find any others that had the same error.

**Comment by scrudgey** [comment]
same interaction bug as lighter, clothes, hats, and containers

**Comment by duckmammal** [comment]
well, i guess there's a 2nd issue around trying to carry the fridge outside the house

**Comment by scrudgey** [comment]
fridge leaving the house is related to issues with non-collectible permanent house objects needing to reset daily.

right now, the house does not reset and the fridge does not collect. if you carry the fridge outside the house then start a new day, you will never have a fridge again. i need to come up with a general solution to this problem.

**Comment by scrudgey** [comment]
this shouldn't have been closed. anyway it's fixed now
