### ISSUE TITLE
Beppo's "put" option unclear

### ISSUE THREAD

**Issue by duckmammal** [scrudgey/yogurt#159]
Bengis is holding an empty pizza box as beppo runs around the studio.
Interacting with Beppo, I find I have to option to "Put"
![image](https://user-images.githubusercontent.com/4755233/78864465-85ac6080-79f0-11ea-9ad9-4bdd51ccac1b.png)

I have selected this option several times, but don't know what effect it is supposed to have, except on the last few times i've gotten the following "it's full" text.

![image](https://user-images.githubusercontent.com/4755233/78864630-d459fa80-79f0-11ea-9b96-253cb2a27d26.png)

**Comment by duckmammal** [comment]
I don't know if this is related to the number of different balloon commands that exist for beppo

**Comment by scrudgey** [comment]
fixed
