### ISSUE TITLE
Unsure of why there are so many balloon commands for Beppo

### ISSUE THREAD

**Issue by duckmammal** [scrudgey/yogurt#160]
Why are there two different spellings of balloon here?
![image](https://user-images.githubusercontent.com/4755233/78864738-184cff80-79f1-11ea-9573-ad2537b0126d.png)

**Comment by duckmammal** [comment]
oh, after some experimentation i have determined that Put is putting items into the pizza box, and that beppo has an infinite number of balloon animals / balloons to add to the pizza box, but the pizza box can only hold two items max.

Asking for a Balloon on the other hand causes Beppo to make a balloon for you.

**Comment by scrudgey** [comment]
yes, although stashing objects should not be an option when you're clicking on someone else (same interaction bug as for clothing, hats, lighter)

**Comment by scrudgey** [comment]
fixed
