### ISSUE TITLE
Requesting a button to stash a held item

### ISSUE THREAD

**Issue by duckmammal** [scrudgey/yogurt#161]
Seriously, it's way too taxing to go click on every single object every time.
just like F is use for a lot of items, R T G or Z could easily be stash.

**Comment by duckmammal** [comment]
Also requesting a button to open inventory (traditionally the i key)

**Comment by scrudgey** [comment]
right clicking on self now stashes currently held object, and "i" hotkey will be in place shortly although i'm trying to think of a more general & flexible hotkey solution.
