### ISSUE TITLE
Squirt Gun can't be filled or sprayed

### ISSUE THREAD

**Issue by duckmammal** [scrudgey/yogurt#162]
Or used in any practical way.. what's with that?

I wanna fill it with different potions that i can then spray on people.

**Comment by scrudgey** [comment]
that is exactly how it should work, hold the squirt gun like any other container (glass jar, etc.) and click on the liquid source, let me know if that works

**Comment by duckmammal** [comment]
yup, that works. but then we have the menuing problem again, which is probably not new

![image](https://user-images.githubusercontent.com/4755233/78914752-b8317a00-7a3f-11ea-8ca8-e39c28f8969b.png)

**Comment by duckmammal** [comment]
but i can't fill the squirt gun with puddle of blood or vomit, which is what i tried the first 3 or times

![image](https://user-images.githubusercontent.com/4755233/78914932-03e42380-7a40-11ea-91b1-69be16e25a88.png)

**Comment by duckmammal** [comment]
![image](https://user-images.githubusercontent.com/4755233/78915221-735a1300-7a40-11ea-93ac-9b11471786d1.png)

**Comment by scrudgey** [comment]
you can't put puddles in containers in general
