### ISSUE TITLE
Duplicating toilets is weird

### ISSUE THREAD

**Issue by duckmammal** [scrudgey/yogurt#164]
The TV can't be duped, i feel like the toilet might deserve the same treatment, considering how they duplicate.

![image](https://user-images.githubusercontent.com/4755233/78866552-6c0d1800-79f4-11ea-8f81-1c44b515e964.png)

**Comment by duckmammal** [comment]
Also, the fridge can't be duped, so that's another argument in favor of the non-dupable toilet.
![image](https://user-images.githubusercontent.com/4755233/78866704-c27a5680-79f4-11ea-8ea3-024e88f23274.png)

**Comment by scrudgey** [comment]
toilet should not be duplicatable or nullifiable

**Comment by scrudgey** [comment]
fixed
