### ISSUE TITLE
items flushed in Yogurt HQ end up in same river as from Bengis' Apartment

### ISSUE THREAD

**Issue by duckmammal** [scrudgey/yogurt#166]
I don't know if this is a feature or a bug
![image](https://user-images.githubusercontent.com/4755233/78867512-12a5e880-79f6-11ea-9c2f-2723c5ac5125.png)

**Comment by scrudgey** [comment]
absolutely 100% an essential puzzle feature

**Comment by scrudgey** [comment]
oh, flushing from hq, that's fine
