### ISSUE TITLE
Changing locations while holding heavy items causes them to be collected

### ISSUE THREAD

**Issue by duckmammal** [scrudgey/yogurt#167]
Normally heavy items are not collectable, which i think is a good thing, but changing the location you are in while holding a heavy item causes it to become collected.

I think you should consider making heavy items neither collectable nor duplicateable.

**Comment by duckmammal** [comment]
![image](https://user-images.githubusercontent.com/4755233/78872698-864bf380-79fe-11ea-90c2-df9dfc3c4ca6.png)

**Comment by scrudgey** [comment]
yes, i became aware of this bug. heavy objects should not be collectable as per the last beta, **except** for the camera (i guess?) so i need to come up with a more general way of excluding certain objects from being collected

**Comment by duckmammal** [comment]
i actually think the camera shouldn't be collectible either since you have the camcorder now, right after you do the mayor commercial.

**Comment by scrudgey** [comment]
fixed, all heavy objects are once again not collectible
