### ISSUE TITLE
Clothes don't maintain dirty state

### ISSUE THREAD

**Issue by duckmammal** [scrudgey/yogurt#168]
If you get blood / draino / paint on your clothes you are normally covered.

![image](https://user-images.githubusercontent.com/4755233/78868263-7381f080-79f7-11ea-9b50-4440c2029b02.png)

changing out of your old clothes makes you clean again (which makes sense)

![image](https://user-images.githubusercontent.com/4755233/78868312-84cafd00-79f7-11ea-8758-f764803d593c.png)

but putting back on your old clothes makes your old clothes look clean

![image](https://user-images.githubusercontent.com/4755233/78868329-96aca000-79f7-11ea-91b2-5c874d6817b1.png)

also, i think that the "smell" of having blood / draino / paint on you are still present after changing clothes because Bengis keeps saying "i don't feel so good" but maybe that's because his health is lower than normal.

**Comment by scrudgey** [comment]
more or less intended behavior
