### ISSUE TITLE
Can set vampire on fire, but he doesn't die

### ISSUE THREAD

**Issue by duckmammal** [scrudgey/yogurt#175]
if you do, you can 'get smoky' while still wearing the fireproof suit.

![image](https://user-images.githubusercontent.com/4755233/78874905-f8720780-7a01-11ea-9e63-778d8026c782.png)

**Comment by scrudgey** [comment]
expected behavior (except for the smouldering fireman outfit)

**Comment by scrudgey** [comment]
can't reproduce (did you start smouldering and then put on the fireman coat?)
