### ISSUE TITLE
you can get the vampire to wear whatever clothes you like

### ISSUE THREAD

**Issue by duckmammal** [scrudgey/yogurt#176]
just hold the clothes, then click the vampire and click the wear button, and he'll put them on.

![image](https://user-images.githubusercontent.com/4755233/78875754-3a4f7d80-7a03-11ea-940b-0e370da6fcfd.png)

![image](https://user-images.githubusercontent.com/4755233/78875855-62d77780-7a03-11ea-87e4-eb68fbf15dbb.png)

![image](https://user-images.githubusercontent.com/4755233/78875939-7da9ec00-7a03-11ea-8880-59f7d73ad07f.png)

![image](https://user-images.githubusercontent.com/4755233/78876102-afbb4e00-7a03-11ea-9312-812e2bc31f31.png)

![image](https://user-images.githubusercontent.com/4755233/78876178-ccf01c80-7a03-11ea-8409-78649d93d8b5.png)

**Comment by duckmammal** [comment]
i think this clothing issue might be something you can merge with the mayor clothing issue

**Comment by duckmammal** [comment]
you can put clothes on just about anyone you come across

![image](https://user-images.githubusercontent.com/4755233/78876611-7505e580-7a04-11ea-8c87-9a38ebcc60f2.png)

![image](https://user-images.githubusercontent.com/4755233/78876933-f493b480-7a04-11ea-8cb2-ed46d727b8d7.png)

**Comment by duckmammal** [comment]
![image](https://user-images.githubusercontent.com/4755233/78877356-93201580-7a05-11ea-9774-a9be6a762507.png)

**Comment by duckmammal** [comment]
Wow, I'm really getting the vibe that this was an intended feature. Dayum and peggle.

**Comment by scrudgey** [comment]
this is actually not intended

**Comment by duckmammal** [comment]
damn, i was into the idea of getting the speedy hat from someone by trading hats with everyone in town.

I don't know how i would get such a sweet hat collection otherwise.

i'll also go ahead and note that wearing the knight's helmet makes you automatically also put on armor.

but then subsequently putting the helmet on others doesn't make them wear armor.

**Comment by scrudgey** [comment]
fixed
