### ISSUE TITLE
Knight's Helmet is not removed when going through oubliette

### ISSUE THREAD

**Issue by duckmammal** [scrudgey/yogurt#179]
![image](https://user-images.githubusercontent.com/4755233/78916407-473f9180-7a42-11ea-85a3-7d13183690a2.png)

**Comment by duckmammal** [comment]
![image](https://user-images.githubusercontent.com/4755233/78916594-8e2d8700-7a42-11ea-88e0-08b90bcec079.png)

**Comment by ryan-foltz-exa** [comment]
intended behavior
