### ISSUE TITLE
Got email about completing moon commercial when i didn't do it

### ISSUE THREAD

**Issue by duckmammal** [scrudgey/yogurt#180]
After completing the vampire commercial...
![image](https://user-images.githubusercontent.com/4755233/78917409-ace04d80-7a43-11ea-94fa-d753ce842721.png)

i got an email congratulating me about completing the moon commercial, even though i've yet to visit the moon

![image](https://user-images.githubusercontent.com/4755233/78917225-71de1a00-7a43-11ea-8d6d-1a47df13cfdc.png)

**Comment by scrudgey** [comment]
fixed
