### ISSUE TITLE
You can put one blender inside another

### ISSUE THREAD

**Issue by duckmammal** [scrudgey/yogurt#181]
But it doesn't blend
![image](https://user-images.githubusercontent.com/4755233/78920553-6f31f380-7a48-11ea-96d6-77df5ac83afa.png)

**Comment by duckmammal** [comment]
guess how many levels of blender-ception im on

![image](https://user-images.githubusercontent.com/4755233/78921178-62fa6600-7a49-11ea-9c01-181b74187bd9.png)

**Comment by duckmammal** [comment]
the answer was 14

**Comment by billfreeman44** [comment]
yo dawg

**Comment by scrudgey** [comment]
fixed
