### ISSUE TITLE
Potion Master not working properly

### ISSUE THREAD

**Issue by duckmammal** [scrudgey/yogurt#182]
![image](https://user-images.githubusercontent.com/4755233/78921538-e916ac80-7a49-11ea-8a8c-51cdb44fdf4c.png)

The potion effect wore off, but it shouldn't if my perk is working the way I think it should.

![image](https://user-images.githubusercontent.com/4755233/78921617-051a4e00-7a4a-11ea-926f-d50d951e85f8.png)

**Comment by ryan-foltz-exa** [comment]
potion master only affects potions you create (need to change text to make this explicit)
