### ISSUE TITLE
peter picklebottom keeps acting weirder as the game goes on

### ISSUE THREAD

**Issue by duckmammal** [scrudgey/yogurt#184]
He exited the cutscene stage left, but then i went to leave the house and he was walking right next to me!

![image](https://user-images.githubusercontent.com/4755233/78923799-a2c34c80-7a4d-11ea-9128-2bc46250dfa5.png)

**Comment by ryan-foltz-exa** [comment]
was he walking to the door to leave at this time?

**Comment by duckmammal** [comment]
yes, but i was overtop him at some point. i wanted to fight him but could press all the keys to punch him at the right time.

**Comment by ryan-foltz-exa** [comment]
this is intended behavior
