### ISSUE TITLE
healthbar freaks out white getting attacked by the knight if i have a potion active

### ISSUE THREAD

**Issue by cccCody** [scrudgey/yogurt#190]
i drank a strength potion and attacked the knight, and got his sword, but he countered and knocked me down. my healthbar went down to a sliver, but then kept jumping back up. i was stuck getting punchedd by the knight forever til i made my head explode

**Comment by cccCody** [comment]
come to think of it, i duplicated the potion and drank several, thinking it would make me EVEN STRONGER!!!

**Comment by scrudgey** [comment]
between this and the oxygen bug i'm realizing something weird is going on with health (unrelated to your potion use) and damage / regeneration appears to be tied to framerate, which is not great

**Comment by scrudgey** [comment]
fixed
