### ISSUE TITLE
Stick and fire issues

### ISSUE THREAD

**Issue by dddanger** [scrudgey/yogurt#196]
There are two separate things that are weird and I don't remember this happening in the previous build:

1. The stick does not always catch on fire in the volcano.
2. The stick does not stay on fire when the scene changes from volcano back to the town.

**Comment by scrudgey** [comment]
were you wearing the firefighters outfit while walking between scenes?

**Comment by dddanger** [comment]
Yes

**Comment by scrudgey** [comment]
fixed
