### ISSUE TITLE
Panelist info was wrong

### ISSUE THREAD

**Issue by duckmammal** [scrudgey/yogurt#200]
I hypnotized dracula and ate a yogurt on camera (while in dracula's body). I submitted my commercial, and a commercial review panelist said they liked it when [My Name] ate a yogurt. I never ate a yogurt, only dracula did.

**Comment by scrudgey** [comment]
Fixed this. Hypnotized characters no longer take on the player's name. If you start a new day as a hypnotized character, the original character will be hanging out in the living room.
