### ISSUE TITLE
Missing the load plane for knight bridge

### ISSUE THREAD

**Issue by duckmammal** [scrudgey/yogurt#202]
I quite often walk too far down and end up missing the loading plane that allows me to go to the stone knight bridge

**Comment by duckmammal** [comment]
![image](https://user-images.githubusercontent.com/4755233/89751037-5c294180-da83-11ea-92c2-46cd41266908.png)

**Comment by duckmammal** [comment]
If I walk too far down before going to the right, I walk right off the screen, and can have a hard time getting her back on the screen.

**Comment by scrudgey** [comment]
fixed
