### ISSUE TITLE
Should Dracula take fire damage like a normal player

### ISSUE THREAD

**Issue by duckmammal** [scrudgey/yogurt#203]
I dunno if this is intentional, or a part of being ethereal or what, but I was wondering if I should be catching on fire / dying here.
![image](https://user-images.githubusercontent.com/4755233/89751131-b62a0700-da83-11ea-826a-0afff465d9b7.png)

I mean, it seems I can catch fire, but that I take no damage.
![image](https://user-images.githubusercontent.com/4755233/89751185-e1acf180-da83-11ea-8131-cccb5ec3b416.png)

**Comment by scrudgey** [comment]
this is actually intended behavior. you are immune to physical damage, but not inflammable. several players are confused by it, but so far it has no gameplay implications I think.
