### ISSUE TITLE
Menuing options

### ISSUE THREAD

**Issue by duckmammal** [scrudgey/yogurt#204]
No way to load a game from the Esc menu. 

Also quit looks like it will "Quit the Game", e.g. exit the game entirely.
Maybe it should read "Quit to main menu" or simply "Main Menu" and then prompt the user if they'd like to save before quitting, and have the options of yes, no, cancel.

**Comment by scrudgey** [comment]
good suggestions

**Comment by scrudgey** [comment]
Quit without save has been wayyyyyy too much of a headache. Now there is only Save and Save & Quit.
