### ISSUE TITLE
No way to delete previous saves from game

### ISSUE THREAD

**Issue by duckmammal** [scrudgey/yogurt#205]
If I make a new game and randomly get assigned the name "srumpi" or whatever, and click go, the game sometimes is like "a character with the name scrumpi already exists." 

It should add a prompt--
Options: Load Old File, Delete Old File, Select New Name 

If you select delete the old file, the next question should be, "Do you want to DELETE the old scrumpi file and make a new one?"
Options: DELETE, Cancel

**Comment by scrudgey** [comment]
fixed
