### ISSUE TITLE
Closet Loadout doesn't work properly after portaling to the magician

### ISSUE THREAD

**Issue by duckmammal** [scrudgey/yogurt#207]
My inventory:
![image](https://user-images.githubusercontent.com/4755233/101814577-31073b00-3ad3-11eb-8fd3-9593de33674b.png)

The things I supposedly loaded:
![image](https://user-images.githubusercontent.com/4755233/101814623-411f1a80-3ad3-11eb-8c7a-6226101bde9d.png)

**Comment by ryan-foltz-exa** [comment]
I can see from this screenshot that all those items were already checked out for the day (they are greyed out), hence you can't retrieve them from the closet until a new day.

**Comment by duckmammal** [comment]
To be fair, I did load these items before visiting the magician, but I feel like I should be able to access the things in my closet once again after returning.

**Comment by duckmammal** [comment]
Like, they were deleted from my inventory after I woke up in bed, while portaling back from the magician

**Comment by ryan-foltz-exa** [comment]
Ah yeah, the magician sequence should reset the closet. Definitely a bug

**Comment by scrudgey** [comment]
fixed
