### ISSUE TITLE
Sometimes an option for an item is unfindable

### ISSUE THREAD

**Issue by duckmammal** [scrudgey/yogurt#210]
After leaving my house I often encounter a package. Most of the time I click on the package immediately, and get something like this:
![image](https://user-images.githubusercontent.com/4755233/101817025-a7f20300-3ad6-11eb-9d3e-98a987c290ef.png)

The thing is, the "open" option is there, but flies off the bottom of the screen. If I walk down, to try to see the "open" option, I see this instead
![image](https://user-images.githubusercontent.com/4755233/101817135-cd7f0c80-3ad6-11eb-8862-384d33449d5e.png)

It seems clear to me from the spacing that the game thinks there should be more than 2 options, but the 3rd option seems to be invisible?!

**Comment by scrudgey** [comment]
fixed
