### ISSUE TITLE
Something didn't load right after completing the mayor commercial

### ISSUE THREAD

**Issue by duckmammal** [scrudgey/yogurt#211]
This is what it looked like when I woke up in the morning and was being shown a new item
![image](https://user-images.githubusercontent.com/4755233/101821933-7d577880-3add-11eb-9e00-cc35924929e0.png)

I wonder if it could be that the game is trying to show me multiple new items at the same time?

**Comment by ryan-foltz-exa** [comment]
This is something wrong with the particle system, I think.

**Comment by scrudgey** [comment]
I think this is fixed?
