### ISSUE TITLE
Chainsaw facing the wrong direction

### ISSUE THREAD

**Issue by duckmammal** [scrudgey/yogurt#212]
I got the chainsaw used it to cut down a tree and some townsfolk, and then put it away

After I took it out again, it was facing the wrong direction. Maybe the same direction I was facing when I put it away last time?
Anyways, now it's always facing the wrong direction.
![image](https://user-images.githubusercontent.com/4755233/101822726-a6c4d400-3ade-11eb-8227-9df578f6f7fe.png)

sorry that it's covered in blood, it's kinda hard to see this way

**Comment by scrudgey** [comment]
fixed
