### ISSUE TITLE
Constantly being referred to by the wrong name

### ISSUE THREAD

**Issue by duckmammal** [scrudgey/yogurt#213]
People keep calling me Tina
![image](https://user-images.githubusercontent.com/4755233/101822888-dd025380-3ade-11eb-9d91-bd28f064668f.png)

When that's not my name
![image](https://user-images.githubusercontent.com/4755233/101822917-e8557f00-3ade-11eb-905a-b1501735480d.png)

**Comment by scrudgey** [comment]
fixed!
