### ISSUE TITLE
imp said drain cleaner wasn't magical

### ISSUE THREAD

**Issue by duckmammal** [scrudgey/yogurt#216]
![image](https://user-images.githubusercontent.com/4755233/101831384-ae8a7580-3aea-11eb-9b2c-5e7bd085e1b0.png)

but then told me to use it in a potion of mindfulness
![image](https://user-images.githubusercontent.com/4755233/101830289-26f03700-3ae9-11eb-9d98-d00beb5873ce.png)

**Comment by scrudgey** [comment]
this is because the imp doesn't check the contents of `LiquidReservoir` for magical status. Should be fixable.

**Comment by scrudgey** [comment]
well now he will analyze the drain cleaner properly, but he will give you the recipe for poison of course.
