### ISSUE TITLE
make the taskbar icon bigger/more recognizable

### ISSUE THREAD

**Issue by cccCody** [scrudgey/yogurt#220]
![its a tiny little dot](https://user-images.githubusercontent.com/753031/103393399-4fab9100-4ad7-11eb-8e54-866c74efd098.png)

**Comment by scrudgey** [comment]
done

<img width="562" alt="Screen Shot 2021-03-14 at 13 36 10" src="https://user-images.githubusercontent.com/11416012/111083344-59d00f80-84ca-11eb-9982-a45122a134ab.png">


<img width="438" alt="Screen Shot 2021-03-14 at 13 35 39" src="https://user-images.githubusercontent.com/11416012/111083347-5f2d5a00-84ca-11eb-83bc-3014a4071c11.png">

**Comment by cccCody** [comment]
hell yeah
