### ISSUE TITLE
Sometimes options are off the screen when in the bottom right

### ISSUE THREAD

**Issue by billfreeman44** [scrudgey/yogurt#224]
The get option here is gone for the hat in the bottom left

![Untitled](https://user-images.githubusercontent.com/7268131/105606462-8dfb3f80-5d67-11eb-96cb-6acb2ee9eb38.png)

**Comment by billfreeman44** [comment]
![Untitled](https://user-images.githubusercontent.com/7268131/105606482-a9664a80-5d67-11eb-8452-a0e210359551.png)

**Comment by scrudgey** [comment]
duplicate of https://github.com/scrudgey/yogurt/issues/229
