### ISSUE TITLE
Eating yogurt in lower hell does not count for the commercials

### ISSUE THREAD

**Issue by billfreeman44** [scrudgey/yogurt#225]
I thought there might be a location called "hell" somewhere but eating it in hell's kitchen and the other hell areas seem to work

**Comment by billfreeman44** [comment]
![Untitled](https://user-images.githubusercontent.com/7268131/105607305-ff3cf180-5d6b-11eb-8116-03bf541e2080.png)

**Comment by scrudgey** [comment]
fixed
