### ISSUE TITLE
Stomach contents visually squished when some menus are open

### ISSUE THREAD

**Issue by billfreeman44** [scrudgey/yogurt#228]
This is just visual. It doesn't really hurt anything.

![Untitled1](https://user-images.githubusercontent.com/7268131/105609519-dcb0d580-5d77-11eb-9dbd-7d471cf5b490.png)

![Untitled2](https://user-images.githubusercontent.com/7268131/105609520-dde20280-5d77-11eb-84da-74ffb285c825.png)

**Comment by scrudgey** [comment]
fixed
