### ISSUE TITLE
"climb" button on ladder in hell's kitchen off right hand side of screen

### ISSUE THREAD

**Issue by billfreeman44** [scrudgey/yogurt#229]
Seems to happen when I come across the bridge

![Untitled](https://user-images.githubusercontent.com/7268131/105614670-b3547180-5d98-11eb-8140-453055a3c023.png)

**Comment by scrudgey** [comment]
thought i'd fixed this, i guess not!!!!

**Comment by scrudgey** [comment]
maybe fixed?
