### ISSUE TITLE
Ended up under the bridge after resurrecting after knight killed me.

### ISSUE THREAD

**Issue by billfreeman44** [scrudgey/yogurt#241]
![Untitled](https://user-images.githubusercontent.com/7268131/108640431-8f538100-7467-11eb-9f76-068c3b16ed80.png)

Not sure if I could leave. knight stun locked me

**Comment by scrudgey** [comment]
getting under the bridge is bad. there's no way out.

**Comment by scrudgey** [comment]
should be fixed
