### ISSUE TITLE
Corrupted save when the wrong item is flushed.

### ISSUE THREAD

**Issue by WarlockD** [scrudgey/yogurt#253]
Not sure how it happened, but currently I have a save In the room right before the sewer level where you mind control the hobo to get him to hell's kitchen.  Some reason I am "above" the entire map, walking on it.  Also when I explode my head, it seems like I cannot enter the area without the entire screen going black.  Not sure why.  I didn't know the code is here so going to pull the save and check it out.  I will put the save here just in case.

Ok, it looks like it has to do with that room and what I flushed down the toliet.  It causes the room to crash and has me restart the day.  So I load up the save and die.  I drink some shakes to get strength, then go to the man hole cover.  When I enter the hole, crash, restart.  Here is the log I will zip up the xml too.  I am betting its one of the items I flushed down the toliet.  Uggh so close to finishing the game too

> loading toilet item cosmic_nullifier (UnityEngine.GameObject)
> 
> loading toilet item stain (UnityEngine.GameObject)
> 
> Load failed, defaulting to new day
> 
> Uploading Crash Report
> NullReferenceException: Object reference not set to an instance of an object
>   at GameManager.SpecificSceneInitialize (System.String sceneName) [0x005af] in <0bbbeaf599d14f32b9b4e3b4b6e065bf>:0 
>   at GameManager.InitializePlayableLevel (System.Boolean loadLevel) [0x001e5] in <0bbbeaf599d14f32b9b4e3b4b6e065bf>:0 
>   at GameManager.SceneWasLoaded (UnityEngine.SceneManagement.Scene scene, 
> UnityEngine.SceneManagement.LoadSceneMode mode) [0x000c5] in <0bbbeaf599d14f32b9b4e3b4b6e065bf>:0 
> UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
> UnityEngine.DebugLogHandler:LogException(Exception, Object)
> UnityEngine.Logger:LogException(Exception, Object)
> UnityEngine.Debug:LogException(Exception)
> GameManager:SceneWasLoaded(Scene, LoadSceneMode)
> UnityEngine.SceneManagement.SceneManager:Internal_SceneLoaded(Scene, LoadSceneMode)

[Player.log](https://github.com/scrudgey/yogurt/files/6643110/Player.log)
[crashdump.zip](https://github.com/scrudgey/yogurt/files/6643112/crashdump.zip)

**Comment by WarlockD** [comment]
Ok, I got a hack that can fix it.  It erases all the toliet items though.  Just clear all the <toiletItems> in the GameData file.

**Comment by scrudgey** [comment]
You are exactly right, good bug hunting. I think I can work around this pretty easily by trying to ignore items that don't load properly. The bugfix will come in the next update

**Comment by scrudgey** [comment]
this should be "fixed" now, in that there's a workaround in the code. I also tried to to fix what I think the actual bug was, but this is untested.
