### ISSUE TITLE
Character appears to be wearing clothes even when there are no clothes

### ISSUE THREAD

**Issue by gopperman** [scrudgey/yogurt#28]
Steps to reproduce:
1. Start new game
2. Open Inventory
3. Select Pajamas
4. Throw Pajamas away
5. Character is still wearing clothes for some reason what the hell man
![image](https://user-images.githubusercontent.com/1591557/57002731-835e4700-6b8f-11e9-8fa2-5c09900bbfd4.png)

**Comment by scrudgey** [comment]
you just pulled pajamas out of your dresser and threw them on the floor

**Comment by gopperman** [comment]
It says dresser because thats where my mouse cursor was when creating the screenshot hth

**Comment by scrudgey** [comment]
resolved
