### ISSUE TITLE
Peter Picklebottom event occurs after "continuing"

### ISSUE THREAD

**Issue by dddanger** [scrudgey/yogurt#30]
Loaded in to peter picklebottom purloining my precious property before I had a chance to stash anything. It's a little unfair is all.

**Comment by scrudgey** [comment]
he'll never take anything you haven't already collected, so nothing is lost permanently

**Comment by scrudgey** [comment]
i'll change it so he doesnt appear on load

**Comment by dddanger** [comment]
The duplicator was greyed out, and I had to reset the inventory by going to sleep for it to return.

**Comment by scrudgey** [comment]
fixed
