### ISSUE TITLE
Eating Blended Eggplant + Yogurt didn't work

### ISSUE THREAD

**Issue by duckmammal** [scrudgey/yogurt#72]
I combined eggplant and yogurt together in the blender and at it, but it only counted as me eating eggplant, so I had to eat the remaining yogurt from the floor.

**Comment by scrudgey** [comment]
i request more detail here. you put an eggplant and yogurt in a blender and turned the power on until the eggplant was blended? or you put these things in the belnder and ate the blender? whats going on

**Comment by duckmammal** [comment]
- Get eggplant
- Power blender (on)
- Lid off
- Stash eggplant in blender
- Get yogurt from table
- Stash yogurt in blender
- Eat blender contents

**Comment by scrudgey** [comment]
you put the entire yogurt cup in the blender? there is a way to just Fill it with the yogurt, which should work as intended

**Comment by duckmammal** [comment]
i think i failed to fill it properly, because adding the ingredients later made a strength potion.
