### ISSUE TITLE
Commands for items persist if struck and you're no longer holding them

### ISSUE THREAD

**Issue by duckmammal** [scrudgey/yogurt#73]
![image](https://user-images.githubusercontent.com/4755233/78458344-6a92c700-7665-11ea-8c88-a5e5ec02d3d7.png)

- Certain items (like articles of clothing) drop when you're struck.
- I was holding a shirt, about to put it on. 
- When punched, with menu still active, I dropped the shirt.
- The menu for the shirt persisted.
- Stash, Wear, and Drop options seemed to have no outward visible effects when selected.
- Throw put "Scrints" in a state of constantly repeating the throwing motion with nothing in hand.
- Walking while throwing causes scrints to remain in the last frame of the "Throw" animation with nothing in hand.

![image](https://user-images.githubusercontent.com/4755233/78458380-a6c62780-7665-11ea-9fdd-d07a1677d8a1.png)

- Getting a new item from inventory caused that item to appear in Scrints' body, while maintaining the state where Scrints was in the throwing motion.
- Being struck caused the item to first, immediately jump to Scrints' hands, and then second, immediately get thrown at the start of the next throw loop.
- This concluded the throw loop.

**Comment by scrudgey** [comment]
hahaha awesome

**Comment by scrudgey** [comment]
fixed
