### ISSUE TITLE
Knocking the chest off a cliff caused it to get stuck in the cliff

### ISSUE THREAD

**Issue by duckmammal** [scrudgey/yogurt#74]
![image](https://user-images.githubusercontent.com/4755233/78458558-26082b00-7667-11ea-80fe-c8e78d910931.png)

- Get strong
- Hit chest off cliff
- Chest is stuck in cliff
- Chest looks different (open?) now

**Comment by duckmammal** [comment]
I dunno if this is an effect of carrying the chest around, or hitting it off a cliff, but the open chest (heavy item) appeared in my closet, which was different from the sewer cap.
![image](https://user-images.githubusercontent.com/4755233/78458942-26ee8c00-766a-11ea-9112-d7745d2c1d6d.png)
I have never opened the chest "normally".

**Comment by scrudgey** [comment]
part of a general known issue about thrown objects interacting with cliff edges
