### ISSUE TITLE
Commanding Apothecar-ist talk to you gives a weird menu

### ISSUE THREAD

**Issue by duckmammal** [scrudgey/yogurt#75]
![image](https://user-images.githubusercontent.com/4755233/78458740-7c299e00-7668-11ea-9b67-8634d00aa3d4.png)

- Talk to shopkeep in apothecary
- choose command
- choose only visible action (assumed "Talk")

Further chat actions all lead to this next menu
![image](https://user-images.githubusercontent.com/4755233/78458770-c7dc4780-7668-11ea-917e-f87a06741fec.png)

you can exit this menu by chosing command again, but the keyboard no longer works.

**Comment by duckmammal** [comment]
(You can no longer e.g. use wasd to walk around)

**Comment by duckmammal** [comment]
Entering fight mode still works.
Pressing F still invokes an attack but items in hand (e.g. sword) are dropped.
![image](https://user-images.githubusercontent.com/4755233/78458843-4802ad00-7669-11ea-9704-504770714a0a.png)

**Comment by scrudgey** [comment]
good catch, you are not supposed to be able to command the imp at all

**Comment by duckmammal** [comment]
![image](https://user-images.githubusercontent.com/4755233/78458856-610b5e00-7669-11ea-9a64-610b97de0ff5.png)
This is the command menu item

**Comment by scrudgey** [comment]
fixed
