### ISSUE TITLE
Knocked myself out of bounds

### ISSUE THREAD

**Issue by duckmammal** [scrudgey/yogurt#77]
![image](https://user-images.githubusercontent.com/4755233/78459023-f4915e80-766a-11ea-804b-27338fa985e8.png)
I was trying to "Unlock" the chest in the mayor's attic by hitting it while strong with a golf club.
I knocked it into the bottom-left corner of the the staircase entrance and then walked in front of it.
I turned Scrints to face up (so her back was to the viewer and she was facing the chest)
I hit the chest with the golf club again (while strong) multiple times, causing slight vibrations to the chest, but no large movement (like it was stuck).
On a final swing, the chest moved violently, flying straight up into the air, so high it went off screen, before appearing to land at the far end of the room.

From this point on WASD caused Scrints to "lean" left or right instead of walking. She could perform no "real" motion (e.g. traversing distance on the ground).
"Explode Head" option was chosen to reset game state, whereupon the chest appeared directly in front of Scrints' gibbed body again.
![image](https://user-images.githubusercontent.com/4755233/78459145-e3951d00-766b-11ea-8734-e66498b21ebb.png)

**Comment by scrudgey** [comment]
general physics fuckery related to #172
