### ISSUE TITLE
Couldn't get Curly  to put down camcorder

### ISSUE THREAD

**Issue by duckmammal** [scrudgey/yogurt#78]
I went to Yogurt HQ
I commanded Curly to get the (recording) camcorder
I commanded Curly to drop the (recording) camcorder
He did not drop it, despite text saying "Why certainly my good man"
I had Scrints punch him until he fell down, at which point the camcorder flew off screen and could not be found or interacted with.
The green "recording" box could no longer be seen.

**Comment by scrudgey** [comment]
lmao

**Comment by duckmammal** [comment]
I think I did a save and quit from this point.
When I came back, I came back to this screen, where the music was playing but where keys didn't do anything.
![image](https://user-images.githubusercontent.com/4755233/78459791-66b87200-7670-11ea-9a4c-b87c11e281ec.png)

**Comment by duckmammal** [comment]
Nothing could be interacted with, although, sign, ladder, etc. could be hovered over.

**Comment by duckmammal** [comment]
was forced to Alt F4 to quit

**Comment by scrudgey** [comment]
lets try to grab your save file. what OS are you using?

**Comment by duckmammal** [comment]
After Exiting and reloading I was in the HQ basement. (I couldn't access the menu to "Resave")

**Comment by duckmammal** [comment]
I'm on Windows.

**Comment by scrudgey** [comment]
we're gonna want

%userprofile%\AppData\Local\Packages\Yogurt Commercial 3\LocalState

or something like that. in there you should see a directory for your character name (scrints). zip and send please TIA

**Comment by scrudgey** [comment]
C:/Users/Username/AppData/LocalLow/CompanyName/GameName ?

**Comment by duckmammal** [comment]
[Scrints.zip](https://github.com/scrudgey/yogurt/files/4432310/Scrints.zip)

**Comment by duckmammal** [comment]
Note that after loading this game (starting in HQ basement) I went home to grab some stuff, and everything looked like Day 1 again.

- I didn't have 3 chests and a camera in front of my closet
- I didn't have a duplicated version of myself (but with no clothes on) walking around
- The blender was back on the counter
- The jar was back on the table
- My bed was unmade (I normally make it every day)

**Comment by duckmammal** [comment]
But also, clothes I had taken out of the dresser earlier in the day (e.g. kaiser helm) could not be taken out again.
Similarly with items taken from the closet.

**Comment by scrudgey** [comment]
yes your game entered an emergency recovery state, something broke when serializing the yogurt hq scene

**Comment by scrudgey** [comment]
fixed
