### ISSUE TITLE
Commanding someone else to leave a place causes you to leave instead 

### ISSUE THREAD

**Issue by duckmammal** [scrudgey/yogurt#79]
Moe was near the drain in Yogurt HQ.
I asked him to Enter the drain
Moe said, "why certainly my good man"
The game acted as if I had just entered the drain, which is counter-intuitive at best
I recommend that players say "I'd rather not" when asked to enter / leave a location.

**Comment by scrudgey** [comment]
yes, makes sense

**Comment by scrudgey** [comment]
fixed
