### ISSUE TITLE
Moving from forest to main area and vice-versa sometimes doesn't let me continue moving

### ISSUE THREAD

**Issue by billfreeman44** [scrudgey/yogurt#80]
So if I'm moving left into the forest, sometimes i'll just stop completely.  When moving right from forest into main area

**Comment by scrudgey** [comment]
like you're holding left, walk into the forest, continue holding left, but are not walking any more?

**Comment by billfreeman44** [comment]
Yes, exactly.  My only input is "move left" or "move right"

Moving up or down or letting go of left/right then pressing again makes it work.

**Comment by scrudgey** [comment]
seems unique to windows platform, more testing on my side needed

**Comment by scrudgey** [comment]
fixed
