### ISSUE TITLE
board room members copying my movement direction??

### ISSUE THREAD

**Issue by billfreeman44** [scrudgey/yogurt#81]
See gif

![ezgif-6-0a8731875a71](https://user-images.githubusercontent.com/7268131/78460419-c756a780-768e-11ea-91f6-6f451f8f011e.gif)

LEMMINGS!

**Comment by scrudgey** [comment]
yeah they're trying to get on camera

**Comment by scrudgey** [comment]
also do your graphics always look like this?

**Comment by billfreeman44** [comment]
yep. They moved well outside of the camera and into the bathroom though.

**Comment by scrudgey** [comment]
if the graphics are always like this that's a much much bigger bug than the camera thing, i think i might know what it is though
