### ISSUE TITLE
Putting on a Second hat causes player to walk down

### ISSUE THREAD

**Issue by duckmammal** [scrudgey/yogurt#82]
I was wearing the fez when i decided to put on the kaiser helm
![image](https://user-images.githubusercontent.com/4755233/78460396-68d0ff80-7675-11ea-925f-8f7435359d4e.png)
Putting the second hat on "pushed Scrints down" towards the bottom of the screen without me pressing any buttons.
![image](https://user-images.githubusercontent.com/4755233/78460471-ef85dc80-7675-11ea-8038-018a8ba2f847.png)
Scrints walked down until she bumped up against a wall, and could walk no further.
Seems like the game is confused and trying to push Scrints away from something, and the physics engine is suggesting down is the best place to go.
Seems counter-intuitive that wearing two hats makes you go "down".

**Comment by scrudgey** [comment]
yes, known bug in the 2.5D physics

**Comment by duckmammal** [comment]
Note that the black spot on the ground is the shadow of the fez.
After the fez falls off of the kaiser helm, the shadow remains under the fez

**Comment by scrudgey** [comment]
fixed
