### ISSUE TITLE
Characters are always translucent for me :( 

### ISSUE THREAD

**Issue by billfreeman44** [scrudgey/yogurt#83]
On windows 10.

![yc3](https://user-images.githubusercontent.com/7268131/78460537-9c208800-768f-11ea-8534-1def48885f6e.png)

**Comment by billfreeman44** [comment]
![yc3-2](https://user-images.githubusercontent.com/7268131/78460566-d558f800-768f-11ea-8b69-9be81e6a70ce.png)

**Comment by billfreeman44** [comment]
![yc3-3](https://user-images.githubusercontent.com/7268131/78460584-fae60180-768f-11ea-857e-bd116f626c41.png)

**Comment by scrudgey** [comment]
when the game starts, what are you graphic quality settings?

**Comment by billfreeman44** [comment]
I don't see any settings?

**Comment by scrudgey** [comment]
this has to do with the anisotropy settings from what I can tell:

<img width="376" alt="Screen Shot 2020-04-04 at 13 40 23" src="https://user-images.githubusercontent.com/11416012/78460919-e5fe7380-7679-11ea-975d-3f2aeb180fa2.png">

so i'll have to figure out how to fix that. the resolution / graphic settings dialogue was removed in a recent unity update (which is fine i always hated that thing) so this will take a bit of digging.

**Comment by scrudgey** [comment]
Fixed by adjusting anisotropy settings defaults
