### ISSUE TITLE
Request for recipe ingredients list

### ISSUE THREAD

**Issue by duckmammal** [scrudgey/yogurt#84]
When the imp analyzes something, it'd be nice if the user didn't have to remember it on their own.
I'd request an in game, self-populating accessible through some sort of menu.

The list should only tell me about ingredients that i've analyzed, and potions that the imp has told me about.

**Comment by scrudgey** [comment]
good idea

**Comment by duckmammal** [comment]
Cool that if you bring the potion to the imp they tell you what it was made from.

**Comment by billfreeman44** [comment]
+rep good idea

**Comment by scrudgey** [comment]
also plan to let the imp analyze the player

**Comment by billfreeman44** [comment]
Suggestion: allow player to put the purple hat on the imp turning it into a pimp

**Comment by scrudgey** [comment]
excellent idea

**Comment by scrudgey** [comment]
added recipe book
