### ISSUE TITLE
Rock covers body when "gotten"

### ISSUE THREAD

**Issue by duckmammal** [scrudgey/yogurt#87]
I guess it has to do with the "center bottom" of the object being in Scrint's hands.
![image](https://user-images.githubusercontent.com/4755233/78460950-31b11d00-767a-11ea-9840-4134f7dd0436.png)

**Comment by scrudgey** [comment]
specifically, stains and hats do exhibit the expected sorting group layer

**Comment by scrudgey** [comment]
fixed
