### ISSUE TITLE
Anchorites go back to hopping after getting in a fight

### ISSUE THREAD

**Issue by duckmammal** [scrudgey/yogurt#88]
I entered the hole and started a fight with the Anchorite monks.
Many were left incapacitated on the ground (but not gibbed)
After leaving the hole and re-entering, they were all hopping on the ground in the position they were left incapacitated, even the prostrate bodies.
![image](https://user-images.githubusercontent.com/4755233/78461112-290d1680-767b-11ea-91fe-2f0dc7a4f9ff.png)

Fighting sounds could also be heard as if they were trying to attack me, but too busy hopping.

**Comment by duckmammal** [comment]
As seen above, their heads also returned to an upright position, independent of their bodies.

**Comment by scrudgey** [comment]
known bug when different components (AI, player, hopping, etc.) try to assume control of the controllable character

this one's on the roadmap but it's a doozy, so it put it off for the early access demo

**Comment by scrudgey** [comment]
this one is finally fixed. total overhaul of controllable interface. anchorite dance brought under the umbrella of AI system (dancing is now an AI priority for certain characters)
