### ISSUE TITLE
Add "loadout" to closet

### ISSUE THREAD

**Issue by duckmammal** [scrudgey/yogurt#91]
It's tedious to collect the same 6 or 7 things from your closet every day.
Maybe in the closet menu, you can let a player customize a loadout, of up to 5 or 10 items they can quickly grab before leaving the house.

I would use this all the time for getting my duplicator, camcorder, stick, strength potion, and yogurt.

Having multiple customize-able loadout slots would also be useful.

My thought is that you would automatically wear any clothes in the loadout and everything else would go in your inventory.

**Comment by scrudgey** [comment]
done
