### ISSUE TITLE
Mayor and Vampire commerical reviews don't have the right text

### ISSUE THREAD

**Issue by dddanger** [scrudgey/yogurt#95]
Mayor and vampire commercial reviews refer to the player character doing random things (text is wrong for this commercial type).

**Comment by scrudgey** [comment]
presumably, you were hypnotizing the vampire and mayor for these commercials? for various reasons, when you hypnotize a character, they take on the player name. this is reflected in the commercial transcripts & details.

i need to think about if it's worth it to make exceptions for commercials, it might make sense.

<img width="396" alt="Screen Shot 2020-04-17 at 22 03 36" src="https://user-images.githubusercontent.com/11416012/79628622-5c2dbc00-80f7-11ea-88ce-db1995080bcf.png">
