### ISSUE TITLE
Potion creation is really weird.

### ISSUE THREAD

**Issue by dddanger** [scrudgey/yogurt#99]
I created poison with the egg and drain cleaner or the egg and paint, placed the poison in the jar, blended the heart, then added the heart-blood to the jar. Instead of creating a potion of undead, it just replaced the poison with heart-blood. This happens ~30% of the time and I don't know why.

**Comment by scrudgey** [comment]
recommend you leave it all in the blender for now, although that should have worked.

**Comment by scrudgey** [comment]
fixed
